//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GisFabriek.WktExporter.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GisFabriek.WktExporter.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding feature did not succeed..
        /// </summary>
        public static string AddingFeatureDidNotSucceedErrorMessage {
            get {
                return ResourceManager.GetString("AddingFeatureDidNotSucceedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste WKT text and add to FeatureLayer.
        /// </summary>
        public static string AddWktWindowTitle {
            get {
                return ResourceManager.GetString("AddWktWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CopyButtonText {
            get {
                return ResourceManager.GetString("CopyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid WKT string..
        /// </summary>
        public static string EnterAValidWktStringMessage {
            get {
                return ResourceManager.GetString("EnterAValidWktStringMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export....
        /// </summary>
        public static string ExportButtonText {
            get {
                return ResourceManager.GetString("ExportButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry bag to WKT is not yet supported.
        /// </summary>
        public static string GeometryBagNotSupportedMessage {
            get {
                return ResourceManager.GetString("GeometryBagNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WKT GeometryCollection to GeometryCollection is not yet supported.
        /// </summary>
        public static string GeometryCollectionNotSupportedMessage {
            get {
                return ResourceManager.GetString("GeometryCollectionNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string ImportButtonText {
            get {
                return ResourceManager.GetString("ImportButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WKT is not a {0}. Please enter a valid {0} WKT string..
        /// </summary>
        public static string InvalidWktTypeMessageTemplate {
            get {
                return ResourceManager.GetString("InvalidWktTypeMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        public static string LayerTextFragment {
            get {
                return ResourceManager.GetString("LayerTextFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed WKT, wrong number of elements, expecting.
        /// </summary>
        public static string MalformedWktWrongNumberOfElelementsFragment {
            get {
                return ResourceManager.GetString("MalformedWktWrongNumberOfElelementsFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Feature selected.
        /// </summary>
        public static string NoFeatureSelectedCaption {
            get {
                return ResourceManager.GetString("NoFeatureSelectedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait....
        /// </summary>
        public static string PleaseWaitMessage {
            get {
                return ResourceManager.GetString("PleaseWaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WKT PolyhedralSurface to MultiPatch is not yet supported.
        /// </summary>
        public static string PolyhedralSurfaceNotSupportedMessage {
            get {
                return ResourceManager.GetString("PolyhedralSurfaceNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string ReadyTextFragment {
            get {
                return ResourceManager.GetString("ReadyTextFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text files (*.txt)|*.txt|All files (*.*)|*.*.
        /// </summary>
        public static string SaveFileDialogFilterText {
            get {
                return ResourceManager.GetString("SaveFileDialogFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Feature..
        /// </summary>
        public static string SelectAFeatureMessage {
            get {
                return ResourceManager.GetString("SelectAFeatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a FeatureLayer..
        /// </summary>
        public static string SelectFeatureLayerMessage {
            get {
                return ResourceManager.GetString("SelectFeatureLayerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one single FeatureLayer having the geometry type of the WKT..
        /// </summary>
        public static string SelectOneSingleFeatureLayerWithCorrectGeometryType {
            get {
                return ResourceManager.GetString("SelectOneSingleFeatureLayerWithCorrectGeometryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated WKT.
        /// </summary>
        public static string ShowWktWindowTitle {
            get {
                return ResourceManager.GetString("ShowWktWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spatial Reference.
        /// </summary>
        public static string SpatialReferenceTextFragment {
            get {
                return ResourceManager.GetString("SpatialReferenceTextFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TypeTextFragment {
            get {
                return ResourceManager.GetString("TypeTextFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported geometry type.
        /// </summary>
        public static string UnsupportedGeometryType {
            get {
                return ResourceManager.GetString("UnsupportedGeometryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WKT could not be converted to a Geometry.
        /// </summary>
        public static string WktCouldNotBeConvertedToGeometryErrorMessage {
            get {
                return ResourceManager.GetString("WktCouldNotBeConvertedToGeometryErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WKT Geometry added as new Feature. Please check the Feature attributes..
        /// </summary>
        public static string WktGeometryAddedMessage {
            get {
                return ResourceManager.GetString("WktGeometryAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WKT is empty.
        /// </summary>
        public static string WktIsEmptyErrorMessage {
            get {
                return ResourceManager.GetString("WktIsEmptyErrorMessage", resourceCulture);
            }
        }
    }
}
